# Generated by Django 4.0.5 on 2022-07-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='related_questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='question',
            name='related_question',
        ),
    ]
