# Generated by Django 4.0.6 on 2022-10-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_game_related_questions_remove_question_hint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='punishment',
            field=models.IntegerField(default=1),
        ),
    ]
