# Generated by Django 4.0.1 on 2022-01-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schmelladmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='punishment',
            field=models.CharField(default='2 slurker', max_length=200),
        ),
    ]
