# Generated by Django 4.0.2 on 2022-03-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schmelladmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
