# Generated by Django 4.0.1 on 2022-01-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schmelladmin', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schmelladmin.game'),
        ),
    ]
