# Generated by Django 4.0.4 on 2022-05-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schmelladmin', '0002_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='read_out_file',
            field=models.FileField(blank=True, upload_to='read-out-files/'),
        ),
    ]
