# Generated by Django 4.0.1 on 2022-01-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schmelladmin', '0003_alter_task_related_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schmelladmin.task')),
            ],
        ),
    ]
