# Generated by Django 4.0 on 2022-01-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schmelladmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='related_question',
            field=models.BooleanField(default=False),
        ),
    ]
