# Generated by Django 4.0 on 2022-01-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schmelladmin', '0002_alter_question_related_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, upload_to='game-pictures/'),
        ),
    ]
