# Generated by Django 4.0.1 on 2022-01-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schmelladmin', '0005_alter_question_related_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='related_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schmelladmin.game'),
            preserve_default=False,
        ),
    ]
