# Generated by Django 4.0.1 on 2022-01-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schmelladmin', '0006_question_related_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='related_week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schmelladmin.week'),
        ),
    ]
