# Generated by Django 4.0 on 2021-12-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPI', '0002_alter_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(upload_to='profile-pictures/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(upload_to='game-pictures/'),
        ),
    ]
