name: Django CI

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test and Collect Static
      env: 
            REDIS_URL: ${{ secrets.REDIS_URL }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            NAME: ${{ secrets.NAME }}
            HOST: ${{ secrets.HOST }}
            PASSWORD: ${{ secrets.PASSWORD }}
            PGPORT: ${{ secrets.PGPORT }}
            DEBUG: ${{ secrets.DEBUG }}
            DISABLE_COLLECTSTATIC: ${{ secrets.DISABLE_COLLECTSTATIC }}
            S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
            SENDGRID_PASSWORD: ${{ secrets.SENDGRID_PASSWORD }}
            SENDGRID_USERNAME: ${{ secrets.SENDGRID_USERNAME }}
            ADMIN_URL: ${{ secrets.ADMIN_URL }}
            ADMIN_DEV_URL: ${{ secrets.ADMIN_DEV_URL }}
      run: |
        echo "REDIS_URL=${REDIS_URL}\nAWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}\nAWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}\n
        DEBUG=${DEBUG}\nDISABLE_COLLECTSTATIC=${DISABLE_COLLECTSTATIC}\nHOST=${HOST}\n
        NAME=${NAME}\nPASSWORD=${PASSWORD}\nPGPORT=${PGPORT}\nS3_BUCKET_NAME=${S3_BUCKET_NAME}\nSECRET_KEY=${SECRET_KEY}\n
        SENDGRID_API_KEY=${SENDGRID_API_KEY}\nSENDGRID_PASSWORD=${SENDGRID_PASSWORD}\nSENDGRID_USERNAME=${SENDGRID_USERNAME}\nUSER=${USER}
        \nADMIN_URL=${ADMIN_URL}\nADMIN_DEV_URL=${ADMIN_DEV_URL}" >> .env
        python manage.py test
        rm -rf staticfiles
        python manage.py collectstatic
        
